import type { Metadata } from "next";
import "./globals.css";
import NavMenu from "./NavMenu";
import { Open_Sans } from "next/font/google";
import AuthProvider from "./AuthProvider";
import Link from "next/link";

const myFont = Open_Sans({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={myFont.className}>
          <div className="container">
            <NavMenu />
            <main>{children}</main>

            <footer>
              
              <ul>
                <li>
                  <Link href={'/about'}>About</Link>
                </li>{' '}
                |
                <li>
                  <Link href={'https://my-portfolio-mmte.vercel.app/'}>
                    Portfolio
                  </Link>
                </li>{' '}
                |
                <li>
                  <Link href={'https://github.com/aidanshotland/myspace'}>Source Code</Link>
                </li>{' '}
                |
                <li>
                  <Link href={'https://nextjs.org'}>NextJS Docs</Link>
                </li>
              </ul>
            </footer>
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
